### ISSUE TITLE
Required parts list

### ISSUE THREAD

**Issue by thisiscetin** [mrjadkowski/SMARS-mini-XL#12]
Can you add the required electronic and mechanical parts used in this robot as a list to README? 
I have checked the design and it looks like everything is there. I just want to order parts same brand as yours, assemble them without a problem. It may also be good to put 3D printing details like infill, support needed, layer height etc. share the experience on parts them also.

**Comment by mrjadkowski** [comment]
The parts listing is in the BOM (Bill of Materials) that is linked in the README. It's a Google Sheets document. Order the 2.x.x parts. If you want to try solar charging get the "future solar charging hardware" as well. That's what I just ordered to try solar charging with mine.

Most of those 3D printing details are on the Thingiverse page, but I like the idea of adding a README to the CAD filed folder here so it is all in one place. The CAD filed folder has the most current design stuff anyways. I'll do that later today.

**Comment by mrjadkowski** [comment]
I added a README to the CAD files folder that has all the details for printing.
