### ISSUE TITLE
AttributeError: object 'module' does not have attribute 'VL53L0X'

### ISSUE THREAD

**Issue by Fredic91** [mrjadkowski/SMARS-mini-XL#15]
Hello
I'm trying to make the mini robot Smars. I printed and assembled everything and started testing the software. (Github files)
I'm a newbie to CircuitPython, usually I code in C / C ++.
I have a problem with this library:
Traceback (most recent calls last):
File "code.py", line 39, in
AttributeError: object 'module' does not have attribute 'VL53L0X'

What do you think?
Thanks

I m using : 
Windows 10
Mu 1.0.2 and Mu 1.1.0.beta.4 
adafruit-circuitpython-bundle-6.x-mpy-20210506
Adafruit CircuitPython 6.2.0 on 2021-04-05;
Adafruit Feather RP2040 with rp2040

**Comment by mrjadkowski** [comment]
Based off your pictures I think you should be using the 2.0.0 code. If that is the case, most likely you don't have the VL530L0X module in the lib folder on your CircuitPy drive

**Comment by mrjadkowski** [comment]
Check the readme in the 2.0.0 release for all the required libraries

**Comment by Fredic91** [comment]
lib/directory VL53L0X only contain a file requirements.txt :
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense
Same for adafruit_neopixel 
Thanks


> 
> 
> Check the readme in the 2.0.0 release for all the required libraries

lib/directory VL53L0X only contain a file requirements.txt :
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense
Same for adafruit_neopixel 
Thanks

**Comment by Fredic91** [comment]
sorry I closed the issue by mistake

    Le samedi 8 mai 2021 à 18:57:18 UTC+2, mrjadkowski ***@***.***> a écrit :  
 
 


Based off your pictures I think you should be using the 2.0.0 code. If that is the case, most likely you don't have the VL530L0X module in the lib folder on your CircuitPy drive
